### ISSUE TITLE
Mpf-examples and Mpf version are out of sync

### ISSUE THREAD

**Issue by MarkRdgOx** [missionpinball/mpf-examples#15]
MPF version on dev branch is 0.55; MPF-EXAMPLES version on dev branch requires MPF 0.54.

**Comment by jabdoa2** [comment]
Why is that so? Do you get an error with mpf-examples dev and mpf dev? If yes which one?

**Comment by MarkRdgOx** [comment]
Mpf-examples _version.py file still specifies 0.54 which gives error son soteup.

**Comment by jabdoa2** [comment]
I see. I forgot that we got a setup.py at all in that repo. Will fix this tomorrow

**Comment by jabdoa2** [comment]
fixed
